### ISSUE TITLE
Caching doesn’t seem to work across multiple builds

### ISSUE THREAD

**Issue by lnolte** [zweitag/middleman-images#21]
I have setup the Gem as described. However I do not optimize images in development mode (only in production) like this `images.optimize = environment?(:development) ? false : false`

My `cache` folder is full of images, but every time I build the project, the Gem optimizes all the images again (even if they haven’t changed). Is this due to the fact that I'm only resizing them in development mode? Is there a way to add optimized images during build to the `cache` folder as well, so images that haven’t changed don’t need to get optimized again every time the project is getting built?

**Comment by pmk1c** [comment]
@lnolte could you update to the current `master` and check again if you problems remains? We have changed a lot of the inner workings of this plugin lately.

**Comment by pmk1c** [comment]
Closing because I think this problem should be fixed. We did much internal optimization, since this bug came up.
