### ISSUE TITLE
Warn when resizing SVGs

### ISSUE THREAD

**Issue by pmk1c** [zweitag/middleman-images#33]
ImageMagick seems to build a new SVG with binary data as base64 in it when called to resize a SVG. Maybe we can fix this by passing the right options to ImageMagick. If not, we should warn about using resize with SVGs, since people probably don't want this behaviour.

**Comment by pmk1c** [comment]
We should do the same for GIFs and provide a way to ignore files with certain extensions.

**Comment by richjdsmith** [comment]
Just being able to disable for SVG's would be fine.

**Comment by pmk1c** [comment]
I think we should do both. We ignore the `resize` option when given a SVG and warn the user about that.
