### ISSUE TITLE
Can not install 

### ISSUE THREAD

**Issue by asecondwill** [zweitag/middleman-images#35]
Installing like this: 

```` gem 'middleman-images' ````

Gives error: 
Could not find gem 'middleman-images' in any of the gem sources listed in your Gemfile.

I can Install like this:
gem 'middleman-images', git: 'https://github.com/zweitag/middleman-images'

Is that recommened?

**Comment by pmk1c** [comment]
@asecondwill The gem hasn't been officially pushed to gem repositories, yet. This will be done, asap.

**Comment by pmk1c** [comment]
Version 0.1.0 has finally been released to the public.
