### ISSUE TITLE
Images are not resized

### ISSUE THREAD

**Issue by asecondwill** [zweitag/middleman-images#36]
Installing like this:

```
Gemfile
gem 'middleman-images', git: 'https://github.com/zweitag/middleman-images'
gem 'image_optim_pack'

config.rb
configure :build do
  activate :images
```
...

And then trying to resize image in template:

```
<%= image_tag "/blog/#{article.date.strftime('%Y')}/#{article.slug}/#{article.data.cover_image}",
     resize: '800x200',
     class: 'blog_thumb' %>
```

Restarting middleman server and checking page, the image tag looks like this:

`<img src="/blog/2019/testing-with-rails-activestorage/testing.jpg" resize="800x200" class="blog_thumb" alt="Testing" width="1000" height="400">`

**Comment by pmk1c** [comment]
The images will currently only get resized when building the page not in Middleman's server mode.

**Comment by asecondwill** [comment]
Thanks for your speedy response : )

I didn't realise that, so i tried agani and checked it, but still not working.

I don't think that is going to be a very good workflow having the resized images only in build.  Makes it hard to develop the site and style the new images, know they are working etc.

**Comment by pmk1c** [comment]
@asecondwill Yes it is. Unfortunately processing ressources on demand in Middleman server mode, is very time consuming. You can enable it by removing the `configure :build` block around the configuration, but you will probably not have a good experience.

We're currently looking for a solution to that problem.

**Comment by asecondwill** [comment]
no probs.  appreciate the trickyness of that.  Ill close this as question answered.
